# Generated by Django 3.1.1 on 2020-09-24 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', max_length=400),
        ),
        migrations.AddField(
            model_name='project',
            name='dateofProject',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 15, 25, 28, 566997, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Technologies', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
