# Generated by Django 3.1.1 on 2020-09-24 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200924_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateofProject',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 15, 34, 31, 673695, tzinfo=utc)),
        ),
    ]
